

DROP TABLE TBL_TEAM CASCADE CONSTRAINTS;
DROP TABLE TBL_PLAYER CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_TEAM_CODE;
DROP SEQUENCE SEQ_PLAYER_CODE;

CREATE TABLE TBL_TEAM
(
    TEAM_CODE    NUMBER CONSTRAINT PK_TEAM_CODE PRIMARY KEY NOT NULL, -- PK
    TEAM_NAME    VARCHAR2(30) NOT NULL,
    LEAGUE_CODE  NUMBER NOT NULL,
    LEAGUE_NAME  VARCHAR2(30) NOT NULL
);

CREATE TABLE TBL_PLAYER
(
    PLAYER_CODE  NUMBER CONSTRAINT PK_PLAYER_CODE PRIMARY KEY NOT NULL, -- PK
    PLAYER_NO    NUMBER NOT NULL,
    PLAYER_NAME  VARCHAR2(30) NOT NULL,
    TEAM_CODE    NUMBER NOT NULL, -- FK
    TEAM_NAME    VARCHAR2(30) NOT NULL,
    LEAGUE_NAME  VARCHAR2(30) NOT NULL,

    CONSTRAINT FK_TEAM_CODE FOREIGN KEY(TEAM_CODE) REFERENCES TBL_TEAM(TEAM_CODE)
);

CREATE SEQUENCE SEQ_TEAM_CODE;
CREATE SEQUENCE SEQ_PLAYER_CODE;

COMMENT ON COLUMN TBL_TEAM.TEAM_CODE IS '구단번호';
COMMENT ON COLUMN TBL_TEAM.TEAM_NAME IS '구단명';
COMMENT ON COLUMN TBL_TEAM.LEAGUE_CODE IS '리그번호';
COMMENT ON COLUMN TBL_TEAM.LEAGUE_NAME IS '리그명';
COMMENT ON TABLE TBL_TEAM IS '구단정보';

COMMENT ON COLUMN TBL_PLAYER.PLAYER_CODE IS '선수코드';
COMMENT ON COLUMN TBL_PLAYER.PLAYER_NO IS '선수번호';
COMMENT ON COLUMN TBL_PLAYER.PLAYER_NAME IS '선수이름';
COMMENT ON COLUMN TBL_PLAYER.TEAM_NAME IS '구단명';
COMMENT ON COLUMN TBL_PLAYER.TEAM_CODE IS '구단번호';
COMMENT ON COLUMN TBL_PLAYER.LEAGUE_NAME IS '리그명';
COMMENT ON TABLE TBL_PLAYER IS '선수정보';


-------------------------
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '맨시티', 1, '프리미어리그');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '리버플', 1, '프리미어리그');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '첼시', 1, '프리미어리그');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '토트넘', 1, '프리미어리그');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '레알마드리드', 2, '라리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '바르셀로나', 2, '라리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '아틀레티코', 2, '라리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '세비야', 2, '라리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '밀란', 3, '세리에 A');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '인테르', 3, '세리에 A');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '나폴리', 3, '세리에 A');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '유벤투스', 3, '세리에 A');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '프랑크푸르트', 4, '분데스리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '바이에른', 4, '분데스리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '도르트문트', 4, '분데스리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '레버쿠젠', 4, '분데스리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '라이프치히', 4, '분데스리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '파리', 5, '리그1');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '마르세유', 5, '리그1');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '포르투', 6, '프리메이라리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '스포르팅CP', 6, '프리메이라리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '아약스', 7, '에레디비시');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '클뤼프 브뤼허', 8, '벨기에프로리그');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '잘츠부르크', 9, '오스트리아분데스리가');
INSERT INTO TBL_TEAM VALUES (SEQ_TEAM_CODE.NEXTVAL, '셀틱', 10, '스코티시프리미어십');

INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 10, '잭 그릴리쉬', 1, '맨시티', '프리미어리그');
INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 19, '훌리안 알바레스', 1, '맨시티', '프리미어리그');
INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 2, '카일 워커', 1, '맨시티', '프리미어리그');
INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 9, '엘링 홀란드', 1, '맨시티', '프리미어리그');
INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 31, '에데르송 모라에스', 1, '맨시티', '프리미어리그');

INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 1, '위고 요리스', 1, '토트넘', '프리미어리그');
INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 17, '크리스티안 로메로', 1, '토트넘', '프리미어리그');
INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 7, '손흥민', 1, '토트넘', '프리미어리그');
INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 14, '이반 페리시치', 1, '토트넘', '프리미어리그');
INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 10, '해리케인', 1, '토트넘', '프리미어리그');
INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 9, '히샬리송', 1, '토트넘', '프리미어리그');
INSERT INTO TBL_PLAYER VALUES (SEQ_PLAYER_CODE.NEXTVAL, 33, '벤 데이비스', 1, '토트넘', '프리미어리그');
commit;